os:
  - linux
  - osx  

language: cpp

compiler:
  - gcc
  - clang


install:
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
      mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      cd ..
    else
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
    fi
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then
      sudo apt-get -y install yasm;
    fi  
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew update;
      brew install yasm;
    fi
      
before_script:
  - mkdir build
  - cd    build

script:
  - cmake -DOpenIGTLink_PROTOCOL_VERSION_3=ON -DOpenIGTLink_SUPERBUILD=OFF -DOpenIGTLink_USE_VP9=ON -DBUILD_TESTING=ON ..
  - make 
  - make test 
  #########################
  # Test for version2 build
  - cmake -DOpenIGTLink_PROTOCOL_VERSION_3=OFF -DOpenIGTLink_SUPERBUILD=OFF  -DOpenIGTLink_USE_VP9=OFF -DBUILD_TESTING=ON ..
  - make
  - make test
  #########################
  # Test for Super build
  - cd ..
  - mkdir SuperBuildTest
  - cd SuperBuildTest
  - cmake -DOpenIGTLink_PROTOCOL_VERSION_3=ON -DOpenIGTLink_SUPERBUILD=ON -DOpenIGTLink_USE_VP9=ON -DBUILD_TESTING=ON ..
  - make
  - cd OpenIGTLink-bin
  - make test


